"""Add product value fields to production weeks

Revision ID: 0c26437441f6
Revises: f8bf4d4c7be7
Create Date: 2025-06-03 09:02:36.817990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c26437441f6'
down_revision = 'f8bf4d4c7be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overall_production_weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecasted_product_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('actual_product_value', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overall_production_weeks', schema=None) as batch_op:
        batch_op.drop_column('actual_product_value')
        batch_op.drop_column('forecasted_product_value')

    # ### end Alembic commands ###
