"""Add display_order to Positions table

Revision ID: 79e2562656ea
Revises: 4f605c6795aa
Create Date: 2025-06-12 13:46:45.144497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text # Import text for raw SQ

# revision identifiers, used by Alembic.
revision = '79e2562656ea'
down_revision = '4f605c6795aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False, server_default=sa.text('999999')))
    # ### end Alembic commands ###

    # --- MANUAL ADDITION TO SET INITIAL ORDER FOR EXISTING RECORDS ---
    # Update existing positions' display_order to their position_id
    op.execute(text('UPDATE positions SET display_order = position_id WHERE display_order = 999999')) # Set 999999 to their ID
    # Alternatively, set to a default value if they were created before server_default was applied
    # op.execute(text("UPDATE positions SET display_order = position_id WHERE display_order IS NULL"))
    # --- END MANUAL ADDITION ---


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('display_order')
    # ### end Alembic commands ###
