"""Add display_order to WorkArea table

Revision ID: 913c869d773d
Revises: 0a8326f898e4
Create Date: 2025-06-06 11:20:26.856655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text # Import text for raw SQL


# revision identifiers, used by Alembic.
revision = '913c869d773d'
down_revision = '0a8326f898e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_areas', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # --- MANUAL ADDITION TO SET INITIAL ORDER ---
    # Update existing work areas' display_order to their work_area_id
    op.execute(text('UPDATE work_areas SET display_order = work_area_id WHERE display_order IS NULL'))
    # --- END MANUAL ADDITION ---


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_areas', 'display_order')
    # ### end Alembic commands ###