"""Make employee display_order not nullable with server default

Revision ID: 960ca0d5c77c
Revises: 913c869d773d
Create Date: 2025-06-10 07:25:49.985213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '960ca0d5c77c'
down_revision = '913c869d773d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.execute(text("UPDATE employees SET display_order = employee_id WHERE display_order IS NULL")) # Or any other unique default
        batch_op.alter_column('display_order', existing_type=sa.Integer(), nullable=False, server_default=sa.text('999999')) # Add server_default here

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('display_order', existing_type=sa.INTEGER(), nullable=True, server_default=None)

    # ### end Alembic commands ###
