"""Add Job, DailyShiftSummary, and FinishingWork models

Revision ID: bcc5ea74fceb
Revises: 9cb72de72c36
Create Date: 2025-06-18 08:32:35.044522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc5ea74fceb'
down_revision = '9cb72de72c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_tag', sa.String(length=100), nullable=False),
    sa.Column('num_sheets', sa.Integer(), nullable=True),
    sa.Column('num_mdf_doors', sa.Integer(), nullable=True),
    sa.Column('linear_meters_edgebanding', sa.Float(), nullable=True),
    sa.Column('num_drawer_boxes', sa.Integer(), nullable=True),
    sa.Column('boxes_mcp', sa.Integer(), nullable=True),
    sa.Column('boxes_pvc', sa.Integer(), nullable=True),
    sa.Column('boxes_paint', sa.Integer(), nullable=True),
    sa.Column('boxes_stain', sa.Integer(), nullable=True),
    sa.Column('boxes_natural', sa.Integer(), nullable=True),
    sa.Column('boxes_glaze', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_tag')
    )
    op.create_table('daily_shift_summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=True),
    sa.Column('sheets_cut_mtr', sa.Integer(), nullable=True),
    sa.Column('sheets_cut_cs43', sa.Integer(), nullable=True),
    sa.Column('mdf_doors_cut_mtr', sa.Integer(), nullable=True),
    sa.Column('mdf_doors_cut_cs43', sa.Integer(), nullable=True),
    sa.Column('edgebanding_ran', sa.Float(), nullable=True),
    sa.Column('edgebanding_changeovers', sa.Integer(), nullable=True),
    sa.Column('manual_edgebanding', sa.Integer(), nullable=True),
    sa.Column('drawer_boxes_built', sa.Integer(), nullable=True),
    sa.Column('boxes_prepped', sa.Integer(), nullable=True),
    sa.Column('boxes_built', sa.Integer(), nullable=True),
    sa.Column('boxes_hung', sa.Integer(), nullable=True),
    sa.Column('team_leader', sa.String(length=100), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('finishing_work',
    sa.Column('finishing_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('manual_part_name', sa.String(length=100), nullable=True),
    sa.Column('finish_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('stage_completed_date', sa.Date(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('finishing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finishing_work')
    op.drop_table('daily_shift_summaries')
    op.drop_table('jobs')
    # ### end Alembic commands ###
