"""Add production weeks and daily hours tables

Revision ID: f8bf4d4c7be7
Revises: 
Create Date: 2025-06-02 13:58:01.545395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bf4d4c7be7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overall_production_weeks',
    sa.Column('overall_production_week_id', sa.Integer(), nullable=False),
    sa.Column('reporting_week_start_date', sa.Date(), nullable=False),
    sa.Column('reporting_week_end_date', sa.Date(), nullable=False),
    sa.Column('forecasted_dollars_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_dollars_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forecasted_boxes_built', sa.Integer(), nullable=True),
    sa.Column('actual_boxes_built', sa.Integer(), nullable=True),
    sa.Column('forecasted_total_production_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_total_production_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('overall_production_week_id'),
    sa.UniqueConstraint('reporting_week_start_date')
    )
    op.create_table('daily_employee_hours',
    sa.Column('daily_hour_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_area_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('forecasted_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('overall_production_week_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['overall_production_week_id'], ['overall_production_weeks.overall_production_week_id'], ),
    sa.ForeignKeyConstraint(['work_area_id'], ['work_areas.work_area_id'], ),
    sa.PrimaryKeyConstraint('daily_hour_id'),
    sa.UniqueConstraint('employee_id', 'work_area_id', 'work_date', 'overall_production_week_id', name='_employee_area_date_week_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_employee_hours')
    op.drop_table('overall_production_weeks')
    # ### end Alembic commands ###
